import React from 'react';
import { Share2, Download, Edit3, Link } from 'lucide-react';

interface ActionButtonsProps {
  tripId?: string;
  tripTitle?: string;
}

const ActionButtons: React.FC<ActionButtonsProps> = ({ tripId, tripTitle = "My Trip" }) => {
  const handleShare = async () => {
    const shareUrl = `${window.location.origin}/final-itinerary/${tripId}`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: tripTitle,
          text: `Check out this amazing travel itinerary: ${tripTitle}`,
          url: shareUrl,
        });
      } catch (error) {
        console.log('Error sharing:', error);
        copyToClipboard(shareUrl);
      }
    } else {
      copyToClipboard(shareUrl);
    }
  };

  const copyToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      alert('Link copied to clipboard!');
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  const handleDownloadPDF = () => {
    // Create a simple PDF download using the browser's print functionality
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>${tripTitle} - Itinerary</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              .header { text-align: center; margin-bottom: 30px; }
              .section { margin-bottom: 20px; }
              .day { margin-bottom: 15px; padding: 10px; border-left: 3px solid #6ECE9D; }
              @media print {
                body { margin: 0; }
                .no-print { display: none; }
              }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>${tripTitle}</h1>
              <p>Generated by Evora - Plan. Share. Inspire.</p>
            </div>
            ${document.querySelector('.container')?.innerHTML || ''}
            <script>
              window.onload = function() {
                window.print();
                window.close();
              }
            </script>
          </body>
        </html>
      `);
      printWindow.document.close();
    }
  };

  const handleEdit = () => {
    // Navigate to edit mode (you can implement this based on your routing)
    window.location.href = '/create-trip';
  };

  return (
    <div className="flex flex-col sm:flex-row gap-4 justify-center">
      <button 
        onClick={handleShare}
        className="flex items-center justify-center gap-2 px-8 py-3 bg-[#6ECE9D] text-black font-medium rounded-lg hover:bg-[#6ECE9D]/90 transition-colors"
      >
        <Share2 className="w-4 h-4" />
        Share Itinerary
      </button>
      
      <button 
        onClick={handleDownloadPDF}
        className="flex items-center justify-center gap-2 px-8 py-3 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors"
      >
        <Download className="w-4 h-4" />
        Download PDF
      </button>
      
      <button 
        onClick={handleEdit}
        className="flex items-center justify-center gap-2 px-8 py-3 bg-gray-100 text-gray-700 font-medium rounded-lg hover:bg-gray-200 transition-colors"
      >
        <Edit3 className="w-4 h-4" />
        Edit Trip
      </button>
    </div>
  );
};

export default ActionButtons;